# Generated by Django 4.1.3 on 2022-12-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='縣市')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100, verbose_name='進港目的')),
                ('scheduled_departure', models.DateTimeField(verbose_name='預定出港日期')),
                ('scheduled_arrival', models.DateTimeField(verbose_name='預定進港日期')),
                ('actual_departure', models.DateTimeField(verbose_name='實際出港日期')),
                ('actual_arrival', models.DateTimeField(verbose_name='實際進港日期')),
                ('form_filling_date', models.DateTimeField(verbose_name='填表日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctno', models.CharField(max_length=10, verbose_name='船編')),
                ('shipname', models.CharField(max_length=20, verbose_name='船名')),
                ('owner', models.CharField(max_length=10, verbose_name='船主')),
                ('contact_no', models.CharField(max_length=10, verbose_name='船主連絡電話')),
                ('address', models.CharField(max_length=100, verbose_name='船主聯絡地址')),
                ('ship_kind', models.CharField(max_length=100, verbose_name='船舶種類')),
                ('tonnage', models.CharField(max_length=1, verbose_name='噸數')),
                ('length', models.PositiveIntegerField(blank=True)),
                ('width', models.PositiveIntegerField(blank=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='港口')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.county')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('job_title', models.CharField(max_length=10, verbose_name='職稱')),
                ('id_num', models.CharField(max_length=10, verbose_name='身分證或護照號碼')),
                ('contact_no', models.CharField(max_length=10, verbose_name='聯絡號碼')),
                ('emergency_contact_person', models.CharField(max_length=10, verbose_name='緊急聯絡人')),
                ('emergency_contact_no', models.CharField(max_length=10, verbose_name='緊急聯絡人聯絡號碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.form')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.port'),
        ),
        migrations.AddField(
            model_name='form',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vessel'),
        ),
    ]
