# Generated by Django 4.1.3 on 2022-12-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='姓名')),
                ('id_no', models.CharField(blank=True, max_length=30, verbose_name='身分證字號')),
                ('passport_no', models.CharField(blank=True, max_length=30, verbose_name='護照號碼')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='聯絡地址')),
                ('residential_no', models.CharField(blank=True, max_length=10, verbose_name='市話')),
                ('mobile_no', models.CharField(blank=True, max_length=10, verbose_name='行動電話')),
                ('fax_no', models.CharField(blank=True, max_length=10, verbose_name='傳真')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='電子信箱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='id_num',
            new_name='id_no',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='shipname',
        ),
        migrations.AddField(
            model_name='form',
            name='signature',
            field=models.ImageField(blank=True, default='signatures/default.png', upload_to='signatures', verbose_name='申請人簽章'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='cert_valid_date',
            field=models.DateField(blank=True, null=True, verbose_name='檢查證書效期(年月日)'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='crew_quota',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='船員配額'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='deepest_draft',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='船舶最深吃水'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='imo',
            field=models.CharField(blank=True, max_length=10, verbose_name='IMO'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='license_valid_date',
            field=models.DateField(blank=True, null=True, verbose_name='來臺特許文件效期(年月日)'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='name_cn',
            field=models.CharField(blank=True, max_length=100, verbose_name='船名(中文)'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='船名(英文)'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='船舶國籍'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='owner_tax_id_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='船舶所有人統編'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='properties',
            field=models.CharField(blank=True, max_length=100, verbose_name='易於辨識特徵'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='ctno',
            field=models.CharField(blank=True, max_length=10, verbose_name='船編'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='長'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, verbose_name='限載成員人數'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='ship_kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='船舶種類'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='tonnage',
            field=models.CharField(blank=True, max_length=1, verbose_name='噸數'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='寬'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vesselowner'),
        ),
    ]
