# Generated by Django 4.1.3 on 2022-11-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='電子信箱')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='帳號')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名(或公司名稱)')),
                ('person_incharge', models.CharField(max_length=30, verbose_name='公司之負責人')),
                ('id_num', models.CharField(max_length=30, verbose_name='申請人或公司負責人身分證字號')),
                ('date_of_birth', models.DateField(verbose_name='出生年月日')),
                ('address', models.CharField(max_length=50, verbose_name='聯絡地址')),
                ('contact_no', models.CharField(max_length=10, verbose_name='連絡電話')),
                ('mobile_no', models.CharField(max_length=10, verbose_name='行動電話')),
                ('fax_no', models.CharField(max_length=10, verbose_name='傳真')),
                ('cert', models.ImageField(default='default.jpg', upload_to='cert_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
