# Generated by Django 4.1.3 on 2022-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='聯絡地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cert',
            field=models.ImageField(default='default.jpg', null=True, upload_to='cert_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(max_length=10, null=True, verbose_name='連絡電話'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='出生年月日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fax_no',
            field=models.CharField(max_length=10, null=True, verbose_name='傳真'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_num',
            field=models.CharField(max_length=30, null=True, verbose_name='申請人或公司負責人身分證字號'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True, verbose_name='行動電話'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='姓名(或公司名稱)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_incharge',
            field=models.CharField(max_length=30, null=True, verbose_name='公司之負責人'),
        ),
    ]
